name: GlassOps Deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        # environment: production # Uncomment to enforce GitHub Environment protection rules

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Required for delta deployments

            - name: Setup GlassOps context
              # Alpha Primitive: https://github.com/glassops-platform/glassops-runtime
              uses: glassops-platform/glassops-runtime@v1
              with:
                  jwt_key: ${{ secrets.SF_JWT_KEY }}
                  client_id: ${{ secrets.SF_CLIENT_ID }}
                  username: ${{ secrets.SF_USERNAME }}
                  instance_url: ${{ secrets.SF_INSTANCE_URL }}

            - name: Deploy with Governance
              uses: glassops-platform/glassops-native-adapter@v1
              with:
                  source-dir: force-app
                  test-level: RunLocalTests
                  deploy-type: Full
                  # min-coverage: 75 # Optional: Override GitHub variables
