name: 'GlassOps Runtime'
description: 'Bootstraps a governed Salesforce execution environment adhering to the GlassOps Protocol.'
author: 'Ryan Bumstead'
branding:
    icon: 'shield'
    color: 'blue'

inputs:
    jwt_key:
        description: 'Private Key for JWT flow'
        required: true
    client_id:
        description: 'External Client App Consumer Key'
        required: true
    username:
        description: 'Target Org Username'
        required: true
    instance_url:
        description: 'Salesforce login URL (e.g., https://login.salesforce.com or https://test.salesforce.com)'
        default: 'https://login.salesforce.com'
        required: false

    enforce_policy:
        description: 'If true, scans devops-config.json before allowing CLI use'
        default: 'true'
        required: false

    test_results:
        description: 'JSON string with test results: {"total": 100, "passed": 95, "failed": 5}'
        required: false

    coverage_percentage:
        description: 'Code coverage percentage (0-100)'
        required: false

    coverage_required:
        description: 'Required coverage percentage threshold'
        default: '80'
        required: false

    plugins:
        description: "Comma-separated list of Salesforce CLI plugins to install (e.g., 'sfdx-hardis,@salesforce/plugin-deploy-retrieve')"
        required: false

    skip_auth:
        description: 'If true, skips Salesforce authentication (useful for CI/governance testing)'
        default: 'false'
        required: false

    config_path:
        description: 'Path to devops-config.json (relative to workspace root)'
        default: 'config/devops-config.json'
        required: false

    otel_endpoint:
        description: 'OTLP endpoint for telemetry export (optional, e.g., http://localhost:4318)'
        required: false

    otel_service_name:
        description: 'Service name for OpenTelemetry traces'
        default: 'glassops-runtime'
        required: false

    otel_headers:
        description: 'Key-value pairs for OTLP exporter headers (e.g., "Authorization=Basic ...")'
        required: false

outputs:
    runtime_id:
        description: 'Unique ID for this execution session'
    org_id:
        description: 'Authenticated Org ID'
    is_locked:
        description: 'True if the environment is currently frozen by policy'
    contract_path:
        description: 'Path to the generated deployment contract JSON file'
    glassops_ready:
        description: 'Indicates if runtime is ready for execution'

runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
        GLASSOPS_JWT_KEY: ${{ inputs.jwt_key }}
        GLASSOPS_CLIENT_ID: ${{ inputs.client_id }}
        GLASSOPS_USERNAME: ${{ inputs.username }}
        GLASSOPS_INSTANCE_URL: ${{ inputs.instance_url }}
        GLASSOPS_ENFORCE_POLICY: ${{ inputs.enforce_policy }}
        GLASSOPS_TEST_RESULTS: ${{ inputs.test_results }}
        GLASSOPS_COVERAGE_PERCENTAGE: ${{ inputs.coverage_percentage }}
        GLASSOPS_COVERAGE_REQUIRED: ${{ inputs.coverage_required }}
        GLASSOPS_PLUGINS: ${{ inputs.plugins }}
        GLASSOPS_SKIP_AUTH: ${{ inputs.skip_auth }}
        GLASSOPS_CONFIG_PATH: ${{ inputs.config_path }}
        OTEL_EXPORTER_OTLP_ENDPOINT: ${{ inputs.otel_endpoint }}
        GLASSOPS_OTEL_SERVICE_NAME: ${{ inputs.otel_service_name }}
        OTEL_EXPORTER_OTLP_HEADERS: ${{ inputs.otel_headers }}